import React from "react";
import { ArrowRight } from "lucide-react";
import { motion } from "framer-motion";

export default function DemoCTA() {
  return (
    <section
      id="demo"
      className="relative overflow-hidden rounded-3xl p-10 bg-gradient-to-br from-indigo-600 via-indigo-500 to-cyan-500 shadow-2xl text-white mt-20"
    >
      {/* Background Image Overlay */}
      <div className="absolute inset-0 opacity-25 bg-[url('https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=60')] bg-cover bg-center"></div>

      {/* Content Wrapper */}
      <div className="relative z-10 flex flex-col lg:flex-row items-center justify-between gap-12">
        {/* Text Section */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
          className="flex-1"
        >
          <h3 className="text-3xl lg:text-4xl font-extrabold leading-tight drop-shadow-sm">
            Boost Your Hiring Workflow with AI-Powered Interviews
          </h3>
          <p className="mt-4 text-indigo-100 max-w-xl text-lg">
            Automate candidate interviews, score answers, and receive structured recommendations —
            all inside a clean, powerful dashboard built for modern HR teams.
          </p>

          {/* Buttons */}
          <div className="mt-8 flex flex-wrap gap-4">
            <button className="px-6 py-3 bg-white text-indigo-700 font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all flex items-center gap-2">
              Request Live Demo <ArrowRight size={18} />
            </button>

            <button className="px-6 py-3 bg-indigo-900/30 border border-white/20 text-white rounded-xl backdrop-blur-md hover:bg-indigo-900/50 transition-all">
              Try Simulation
            </button>
          </div>
        </motion.div>

        {/* AI Summary Box */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="w-full max-w-sm bg-white/10 backdrop-blur-xl p-6 rounded-2xl border border-white/20 shadow-xl"
        >
          <div className="text-sm text-indigo-200">AI Summary Example</div>

          <div className="mt-2 text-lg font-semibold text-white">Candidate: Ayesha Khan</div>

          <div className="mt-4 text-indigo-100 space-y-1 text-sm leading-relaxed">
            <p>
              <span className="font-semibold text-white">Communication:</span> Excellent
            </p>
            <p>
              <span className="font-semibold text-white">Task Management:</span> Very Good
            </p>
            <p>
              <span className="font-semibold text-white">Overall Fit:</span> Strong Candidate
            </p>
          </div>

          <div className="mt-4 text-xs text-indigo-200 opacity-80">
            (Sample evaluation generated by AI)
          </div>
        </motion.div>
      </div>
    </section>
  );
}